# Generated by Django 4.2.7 on 2024-04-27 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_address_customuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='order',
            name='related_documents',
            field=models.FileField(blank=True, null=True, upload_to='order_documents/'),
        ),
    ]
