# Generated by Django 4.2.7 on 2024-04-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_orderdate_order_related_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='elderly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.elderlyprofile'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='related_documents',
        ),
        migrations.AlterField(
            model_name='order',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_orders', to='main.volunteerprofile'),
        ),
        migrations.CreateModel(
            name='RelatedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='order_documents/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='related_documents',
            field=models.ManyToManyField(blank=True, related_name='orders', to='main.relateddocument'),
        ),
    ]
