# Generated by Django 4.2.7 on 2024-05-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_elderly_remove_order_related_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
